name: "Version Releases"
run-name: "Version Releases v${{ inputs.version }}"

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to be published (#.#.#)"
        required: true

jobs:
  validate_actor:
    uses: crajapakshe/devops-tools/.github/workflows/is_authorized_user.yml@main

  version-bump:
    permissions:
      contents: write
      pull-requests: write
    uses: crajapakshe/devops-tools/.github/workflows/versionRelease.yml@main
    with:
      version: ${{ github.event.inputs.version }}
      version_script: "npm run version:changelog --"
    secrets:
      DEVOPS_PAT: ${{ secrets.DEVOPS_PAT }}
